variables:
  SampleName: SssrSample  
  GIT_SUBMODULE_STRATEGY: normal
  CMakeConfig: -G "Visual Studio 16 2019" -A x64

stages:
  - build
  - deploy

build_dx12:
  tags:
  - windows
  - amd64
  stage: build
  script:
  - 'cmake -S sample -B sample/build/DX12 -DGFX_API=DX12 %CMakeConfig%'
  - 'cmake --build sample/build/DX12 --config Release'
  artifacts:
      paths:
      - sample/bin/

build_vk:
  tags:
  - windows
  - amd64
  stage: build
  script:
  - 'cmake -S sample -B sample/build/VK -DGFX_API=VK %CMakeConfig%'
  - 'cmake --build sample/build/VK --config Release'
  artifacts:
      paths:
      - sample/bin/

package_sample:
  tags:
  - windows
  - amd64
  stage: deploy
  dependencies:
    - build_dx12
    - build_vk
  script:
  - copy %VULKAN_SDK%\Bin\glslc.exe .\sample\bin
  - xcopy .\ffx-dnsr\docs\*.pdf .\docs /sy
  - echo "Packaging build"
  - echo cd .\sample\bin\ > %SampleName%_DX12.bat
  - echo start %SampleName%_DX12.exe >> %SampleName%_DX12.bat  
  - echo cd .\sample\bin\ > %SampleName%_VK.bat
  - echo start %SampleName%_VK.exe >> %SampleName%_VK.bat  
  artifacts:
      name: "%SampleName%-%CI_COMMIT_TAG%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHORT_SHA%"
      paths:
      - NOTICES.txt
      - sample/README.md
      - sample/screenshot.png
      - sample/bin/
      - sample/media/
      - docs/
      - "%SampleName%_DX12.bat"
      - "%SampleName%_VK.bat"